# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57fc47daf25e1d28181557816951caf3070a2adbae0f39a72ccb7391e1ba8bd18bbde2c7635dfb42b656a7c6023118c9316d6bf51175f6dfb0c04f9078e99c30

test:
  secret_key_base: db956582de68e70be2a308eb8151b5a53b5e762524ec9645beb5053a9cab42b7ad0cb1380800996de652b528b4cbf7fdc9c7b79b59fe27a2a230900ce5b7c678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
